[build]
builder = "nixpacks"

[deploy]
region = "us-west1"
startCommand = "gunicorn -c gunicorn.conf.py wsgi:application"
healthcheckPath = "/auth/login"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
