"""add priority rules

Revision ID: 9d879dbed828
Revises: f5c7ec753d90
Create Date: 2026-05-14 14:54:45.995588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d879dbed828'
down_revision = 'f5c7ec753d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('set_priority', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stop_on_match', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('priority_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priority_rules_priority_order'), ['priority_order'], unique=False)

    op.create_table('priority_rule_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('group_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['priority_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('priority_rule_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priority_rule_groups_rule_id'), ['rule_id'], unique=False)

    op.create_table('priority_rule_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('value_id', sa.Integer(), nullable=True),
    sa.Column('value_str', sa.String(length=100), nullable=True),
    sa.Column('condition_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['priority_rule_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('priority_rule_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priority_rule_conditions_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priority_rule_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priority_rule_conditions_group_id'))

    op.drop_table('priority_rule_conditions')
    with op.batch_alter_table('priority_rule_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priority_rule_groups_rule_id'))

    op.drop_table('priority_rule_groups')
    with op.batch_alter_table('priority_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priority_rules_priority_order'))

    op.drop_table('priority_rules')
    # ### end Alembic commands ###
